/**
 * CineGeny Business Tools
 * Email IA, Facturation, Traduction, Banque d'images.
 * 7 specialized agents.
 */

// ─── 7 Business Agents ─────────────────────────────────────────────

export interface BusinessAgent {
  slug: string; name: string; role: string; description: string; icon: string; color: string
}

export const BUSINESS_AGENTS: BusinessAgent[] = [
  { slug: 'cg-email-writer', name: 'Email Writer', role: 'Pro email writing', description: 'Writes professional emails tailored to film: investor pitches, casting invitations, distributor follow-ups, press releases.', icon: 'mail', color: '#3B82F6' },
  { slug: 'cg-email-designer', name: 'Email Designer', role: 'Templates & signatures', description: 'Creates elegant email templates and professional HTML signatures with CineGeny branding.', icon: 'palette', color: '#8B5CF6' },
  { slug: 'cg-sequence-planner', name: 'Sequence Planner', role: 'Automated sequences', description: 'Designs automated email sequences: onboarding, follow-up, nurturing. Optimizes open and click rates.', icon: 'git-branch', color: '#10B981' },
  { slug: 'cg-invoice-manager', name: 'Gestionnaire Factures', role: 'Facturation & devis', description: 'Generates compliant quotes and invoices, automatic VAT calculation, payment tracking and reminders.', icon: 'file-text', color: '#F59E0B' },
  { slug: 'cg-translator', name: 'Traducteur Culturel', role: 'Traduction & adaptation', description: 'Translates with cultural finesse. Detects sensitivities (religion, politics, local humor) and adapts the content for each market.', icon: 'languages', color: '#EC4899' },
  { slug: 'cg-subtitle-master', name: 'Subtitle master', role: 'Sous-titrage & doublage', description: 'Specialized in film subtitling: timing, character constraints, language register, lip-sync for dubbing.', icon: 'captions', color: '#06B6D4' },
  { slug: 'cg-image-curator', name: 'Curateur Visuel', role: 'Banque d\'images & moodboards', description: 'Searches and selects images for moodboards, presentations and film lookbooks. Unsplash integration.', icon: 'image', color: '#EF4444' },
]

// ─── 15 Email Templates (complete, ready to send) ────────────────

export interface EmailTemplate {
  id: string; name: string; category: string; subject: string; body: string; variables: string[]
}

export const EMAIL_TEMPLATES: EmailTemplate[] = [
  { id: 'welcome', name: 'Bienvenue', category: 'onboarding', subject: 'Bienvenue sur CineGeny, {name} ! 🎬', body: `Hello {name},\n\nWelcome to the CineGeny adventure!\n\nYou've just joined the first AI-powered collaborative cinema platform. Here are your first steps:\n\n1. 🎭 Complete your creator profile\n2. 🎬 Explore films in production\n3. 🗳️ Vote for your favorite projects\n4. 🤖 Discover our 22 AI cinema agents\n\nYour account is credited with 2 free credits to try our AI tools.\n\nSee you soon on CineGeny,\nThe CineGeny team`, variables: ['name'] },

  { id: 'first-steps', name: 'First Steps (D+2)', category: 'onboarding', subject: '{name}, have you explored the creative studio? 🎨', body: `Hello {name},\n\nHere are 3 things you can do today on CineGeny:\n\n🎬 Create your first film project\nOur AI assistant guides you step by step.\n\n🤖 Chat with an AI cinema agent\n22 specialized agents at your service.\n\n📸 Generate a film poster with your face\nOur Poster Maker creates pro posters in 30 seconds.\n\nNeed help? Just reply to this email.\n\nCreatively,\nThe CineGeny team`, variables: ['name'] },

  { id: 'success-story', name: 'Success Story (J+5)', category: 'onboarding', subject: 'How {creatorName} created their film on CineGeny 🌟', body: `Hello {name},\n\n{creatorName} used CineGeny to create "{filmTitle}" — a {genre} voted for by 847 community members.\n\nTheir journey:\n• Screenplay written with the AI Screenwriter agent\n• Storyboard generated by the creative studio\n• Trailer assembled automatically\n• Successful crowdfunding\n\n"CineGeny let me make my filmmaking dream come true without a Hollywood budget."\n\nYour turn!\n\nThe CineGeny team`, variables: ['name', 'creatorName', 'filmTitle', 'genre'] },

  { id: 'investor-pitch', name: 'Investor Pitch', category: 'business', subject: 'CineGeny — AI cinema investment opportunity', body: `Dear {investorName},\n\nI'm reaching out because {reason}.\n\nCineGeny is the first AI-powered collaborative cinema platform:\n\n📊 Key figures:\n• {userCount} registered creators\n• {filmCount} films in production\n• 0% commission model on AI tokens\n• Revenue model: subscriptions + AI credits\n\n💡 Our edge:\nWe democratize filmmaking with 71 specialized AI agents.\n\nWould you be available for a 20-minute call next week?\n\nBest regards,\n{senderName}\nFounder, CineGeny`, variables: ['investorName', 'reason', 'userCount', 'filmCount', 'senderName'] },

  { id: 'distributor-outreach', name: 'Distributor Outreach', category: 'business', subject: 'CineGeny catalog — Original films for your network', body: `Hello {distributorName},\n\nCineGeny produces original films through its community of creators and AI.\n\nOur current catalog includes {filmCount} films, among them {topFilm} which received {voteCount} community votes.\n\nWe're looking for distribution partners for:\n• VOD / SVOD\n• Television\n• Festivals\n\nCould we arrange a private screening?\n\nBest regards,\n{senderName}`, variables: ['distributorName', 'filmCount', 'topFilm', 'voteCount', 'senderName'] },

  { id: 'casting-invitation', name: 'Invitation Casting', category: 'production', subject: 'Invitation casting — "{filmTitle}" by CineGeny', body: `Hello {actorName},\n\nWe're preparing the casting of \"{filmTitle}\", a {genre} produced on the CineGeny platform.\n\nRole: {roleName}\nDescription: {roleDescription}\n\nShooting is planned for {shootingDates}.\n\nIf you're interested, please send us your CV and a demo reel.\n\nBest regards,\n{senderName}\nCasting, CineGeny`, variables: ['actorName', 'filmTitle', 'genre', 'roleName', 'roleDescription', 'shootingDates', 'senderName'] },

  { id: 'press-release', name: 'Press release', category: 'communication', subject: '[CP] {headline}', body: `PRESS RELEASE\n\n{headline}\n\n{city}, {date} — {leadParagraph}\n\n{bodyText}\n\nAbout CineGeny:\nCineGeny is the first AI-powered collaborative cinema platform. It lets anyone create, fund and distribute films with 71 specialized AI agents.\n\nPress contact:\n{pressContact}\n{pressEmail}`, variables: ['headline', 'city', 'date', 'leadParagraph', 'bodyText', 'pressContact', 'pressEmail'] },

  { id: 'newsletter-film', name: 'Newsletter Film', category: 'newsletter', subject: '🎬 CineGeny Weekly — {weekHighlight}', body: `📬 CineGeny Weekly\n\n🎬 FILM OF THE WEEK\n{featuredFilm} — {featuredDescription}\n\n🏆 TOP VOTES\n{topVotedList}\n\n🤖 AGENT SPOTLIGHT\nThis week, discover {agentName}: {agentDescription}\n\n📊 BY THE NUMBERS\n• {newUsers} new creators\n• {newFilms} new projects\n• {totalVotes} votes this week\n\n👉 Log in: cinegeny.com\n\nSee you next week!\nThe CineGeny team`, variables: ['weekHighlight', 'featuredFilm', 'featuredDescription', 'topVotedList', 'agentName', 'agentDescription', 'newUsers', 'newFilms', 'totalVotes'] },

  { id: 'premiere-promo', name: 'Premiere promo', category: 'event', subject: '🎬 "{filmTitle}" premiere — You\'re invited!', body: `{name},\n\nYou're cordially invited to the premiere of\n\n🎬 \"{filmTitle}\"\nA {genre} film produced by the CineGeny community\n\n📅 {date}\n📍 {location}\n🕐 {time}\n\nDress code: {dressCode}\n\nReserve your seat: {rsvpLink}\n\nWe can't wait to see you there!\n\nThe CineGeny team`, variables: ['name', 'filmTitle', 'genre', 'date', 'location', 'time', 'dressCode', 'rsvpLink'] },

  { id: 'investor-followup', name: 'Relance Investisseur', category: 'business', subject: 'Following up on our conversation — CineGeny', body: `Dear {investorName},\n\nFollowing our {lastInteraction}, I wanted to circle back.\n\nSince our last exchange:\n{updates}\n\nWe'd be glad to continue the discussion. Are you available {proposedDate}?\n\nBest regards,\n{senderName}`, variables: ['investorName', 'lastInteraction', 'updates', 'proposedDate', 'senderName'] },

  { id: 'task-notification', name: 'Task notification', category: 'platform', subject: '⚡ New task available — {taskTitle}', body: `Hello {name},\n\nA new creative task is available for you:\n\n⚡ {taskTitle}\n🎬 Film: {filmTitle}\n💰 Reward: {reward}\n⏰ Deadline: {deadline}\n\nGo to the task: {taskLink}\n\nHappy creating!\nCineGeny`, variables: ['name', 'taskTitle', 'filmTitle', 'reward', 'deadline', 'taskLink'] },

  { id: 'vote-result', name: 'Vote result', category: 'platform', subject: '🗳️ Vote results — "{filmTitle}"', body: `Hello {name},\n\nThe vote results are in!\n\n🎬 \"{filmTitle}\"\n✅ Result: {result}\n📊 Votes: {voteCount}\n🏆 Score: {score}/10\n\n{resultMessage}\n\nThank you for taking part!\nCineGeny`, variables: ['name', 'filmTitle', 'result', 'voteCount', 'score', 'resultMessage'] },

  { id: 'low-balance', name: 'Low Balance Alert', category: 'platform', subject: '⚠️ Your credit balance is low', body: `Hello {name},\n\nYour CineGeny credit balance is {balance} credits.\n\nTo keep using the AI agents and creation tools, top up your account.\n\n💰 Reminder: 0% commission — you only pay the real cost of the AI tokens.\n\nTop up: {rechargeLink}\n\nCineGeny`, variables: ['name', 'balance', 'rechargeLink'] },

  { id: 'referral-success', name: 'Referral successful', category: 'platform', subject: '🎉 {referredName} joined CineGeny thanks to you!', body: `Congratulations {name}!\n\n{referredName} just signed up to CineGeny with your referral code.\n\n🎁 Your rewards:\n• +5 AI credits\n• +100 XP\n\nKeep inviting your friends: {referralLink}\n\nThanks for growing the community!\nCineGeny`, variables: ['name', 'referredName', 'referralLink'] },

  { id: 'partnership-proposal', name: 'Proposition Partenariat', category: 'business', subject: 'Proposition de partenariat — CineGeny x {partnerCompany}', body: `Dear {partnerName},\n\nCineGeny is looking for partners for {partnershipGoal}.\n\nOur platform brings together:\n• {userCount} creators\n• 71 AI cinema agents\n• A unique 0% commission model\n\nWe believe a collaboration with {partnerCompany} could {mutualBenefit}.\n\nWould you be interested in an initial conversation?\n\nBest regards,\n{senderName}\nCineGeny`, variables: ['partnerName', 'partnerCompany', 'partnershipGoal', 'userCount', 'mutualBenefit', 'senderName'] },
]

// ─── Email Signatures ───────────────────────────────────────────────

export interface EmailSignature {
  id: string; name: string; style: string; html: string
}

export const EMAIL_SIGNATURES: EmailSignature[] = [
  { id: 'classic', name: 'Classique', style: 'minimal', html: `<div style="font-family:Arial;font-size:13px;color:#333;border-top:2px solid #E50914;padding-top:12px;margin-top:20px"><strong style="color:#1A1A2E">{name}</strong><br/><span style="color:#666">{title} — CineGeny</span><br/><span style="color:#999;font-size:11px">{email} | {phone}</span><br/><a href="https://cinegeny.com" style="color:#E50914;font-size:11px">cinegeny.com</a></div>` },
  { id: 'modern', name: 'Moderne', style: 'bold', html: `<table style="font-family:Arial;font-size:13px"><tr><td style="border-right:3px solid #E50914;padding-right:15px"><strong style="font-size:16px;color:#1A1A2E">{name}</strong><br/><span style="color:#E50914">{title}</span></td><td style="padding-left:15px"><span style="color:#666">CineGeny — AI Collaborative Cinema</span><br/><span style="color:#999;font-size:11px">{email}</span><br/><a href="https://cinegeny.com" style="color:#E50914;font-size:11px">cinegeny.com</a></td></tr></table>` },
  { id: 'minimal', name: 'Minimaliste', style: 'clean', html: `<div style="font-family:Arial;font-size:12px;color:#999;margin-top:20px">— {name} | {title} | CineGeny | <a href="https://cinegeny.com" style="color:#E50914">cinegeny.com</a></div>` },
]

// ─── Onboarding Sequence ────────────────────────────────────────────

export interface SequenceStep { day: number; templateId: string; trigger: string }

export const ONBOARDING_SEQUENCE: SequenceStep[] = [
  { day: 0, templateId: 'welcome', trigger: 'Inscription' },
  { day: 2, templateId: 'first-steps', trigger: 'J+2 automatique' },
  { day: 5, templateId: 'success-story', trigger: 'J+5 automatique' },
]

// ─── Invoice Config ─────────────────────────────────────────────────

export interface InvoiceLineItem { description: string; quantity: number; unitPrice: number; vatRate: number }

export const VAT_RATES = [
  { id: 'fr-standard', label: 'TVA France 20%', rate: 20, country: 'FR' },
  { id: 'fr-reduced', label: 'TVA France 10%', rate: 10, country: 'FR' },
  { id: 'fr-super-reduced', label: 'TVA France 5.5%', rate: 5.5, country: 'FR' },
  { id: 'de-standard', label: 'MwSt Allemagne 19%', rate: 19, country: 'DE' },
  { id: 'uk-standard', label: 'VAT UK 20%', rate: 20, country: 'GB' },
  { id: 'us-none', label: 'USA (no federal VAT)', rate: 0, country: 'US' },
  { id: 'il-standard', label: 'VAT Israel 17%', rate: 17, country: 'IL' },
]

export const INVOICE_STATUSES = [
  { id: 'draft', label: 'Brouillon', color: '#6B7280' },
  { id: 'sent', label: 'Sent', color: '#3B82F6' },
  { id: 'paid', label: 'Paid', color: '#10B981' },
  { id: 'overdue', label: 'En retard', color: '#EF4444' },
  { id: 'cancelled', label: 'Cancelled', color: '#9CA3AF' },
]

// ─── Translation Languages ──────────────────────────────────────────

export interface TranslationLanguage {
  code: string; name: string; flag: string; nativeName: string
  sensitivityNotes: string[]  // Cultural sensitivities to watch for
}

export const TRANSLATION_LANGUAGES: TranslationLanguage[] = [
  { code: 'en', name: 'Anglais', flag: '🇬🇧', nativeName: 'English', sensitivityNotes: ['US vs UK spelling', 'Inclusive language expectations vary by market'] },
  { code: 'es', name: 'Espagnol', flag: '🇪🇸', nativeName: 'Español', sensitivityNotes: ['Spain vs Latin America (different vocabulary)', 'Informal vs formal address varies by country'] },
  { code: 'de', name: 'Allemand', flag: '🇩🇪', nativeName: 'Deutsch', sensitivityNotes: ['WWII historical sensitivity', 'Sie/Du formality matters'] },
  { code: 'it', name: 'Italien', flag: '🇮🇹', nativeName: 'Italiano', sensitivityNotes: ['Religious references common but use sparingly', 'Regional humor varies widely'] },
  { code: 'pt', name: 'Portugais', flag: '🇧🇷', nativeName: 'Português', sensitivityNotes: ['Portugal vs Brazil (very different vocabulary and culture)', 'Racial references to adapt carefully'] },
  { code: 'ar', name: 'Arabe', flag: '🇸🇦', nativeName: 'العربية', sensitivityNotes: ['High religious sensitivity', 'Romantic/sexual content to adapt', 'Highly varied dialects (MSA vs colloquial)', 'Right-to-left layout'] },
  { code: 'ja', name: 'Japonais', flag: '🇯🇵', nativeName: '日本語', sensitivityNotes: ['Niveaux de politesse (keigo) essentiels', 'Cultural references to localize, not translate', 'Very different humor'] },
  { code: 'ko', name: 'Korean', flag: '🇰🇷', nativeName: '한국어', sensitivityNotes: ['Social hierarchy in the language', 'North Korea/Japan sensitivity', 'Strict formality levels'] },
  { code: 'zh', name: 'Chinois (Mandarin)', flag: '🇨🇳', nativeName: '中文', sensitivityNotes: ['Censure politique (Taiwan, Tibet, Tiananmen)', 'Simplified (mainland) vs traditional (Taiwan/HK)', 'Number superstitions (4 = death)'] },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी', sensitivityNotes: ['Multi-faith religious sensitivity', 'Avoid caste references', 'India/Pakistan partition = sensitive topic'] },
  { code: 'ru', name: 'Russe', flag: '🇷🇺', nativeName: 'Русский', sensitivityNotes: ['Sensitive current geopolitical context', 'Use Soviet historical references sparingly', 'ты/вы formality matters'] },
  { code: 'tr', name: 'Turc', flag: '🇹🇷', nativeName: 'Türkçe', sensitivityNotes: ['Armenia/Kurdish/Cyprus sensitivity', 'Secularism vs religion = divisive topic', 'Honneur et famille = valeurs centrales'] },
]

// ─── Unsplash Config ────────────────────────────────────────────────

export const UNSPLASH_CATEGORIES = [
  { id: 'cinema', label: 'Cinema', query: 'cinema film movie', icon: '🎬' },
  { id: 'landscape', label: 'Paysages', query: 'landscape nature cinematic', icon: '🏔️' },
  { id: 'urban', label: 'Urbain', query: 'city urban night neon', icon: '🌃' },
  { id: 'portrait', label: 'Portraits', query: 'portrait face dramatic lighting', icon: '👤' },
  { id: 'interior', label: 'Interiors', query: 'interior room moody', icon: '🏠' },
  { id: 'texture', label: 'Textures', query: 'texture abstract dark', icon: '🎨' },
  { id: 'mood', label: 'Ambiances', query: 'moody atmospheric fog', icon: '🌫️' },
  { id: 'action', label: 'Action', query: 'action movement speed', icon: '💥' },
]
